---
title: "Figure 5 final PR curves"
author: "Pierre-Luc"
date: "2025-03-27"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(patchwork)
  library(cowplot)
})
source("../functions.R")
```

```{r, fig.width=12, fig.height=7}
load("../03_simulation1/simulated.lfcRes.RData")
st1 <- st
load("../02_MSdata/lfc_res.rds")
stLFC <- mergeSts(st1, st)
stLFC <- stLFC[stLFC$score=="padj.PAS.LSL.loc",]
stLFC$score <- "bbhw PA-shrunkLFC (gBH.LSL)"

load("plotDat.RData", verbose=TRUE)
stSig <- mergeSts(sts, st)
stSig <- stSig[stSig$score %in% c("padj.PAS.LSL.loc","FDR"),]
stSig$score <- gsub("padj.+","bbhw PAS (gBH.LSL)", stSig$score)
stSig$score <- gsub("FDR","standard", stSig$score)
st <- rbind(stSig, stLFC)

tpr <- tprPlot(st) + scale_color_manual(values=setNames(RColorBrewer::brewer.pal(3, "Dark2"),unique(st$score)))
```



```{r}
dea <- readRDS("../00_stressData/CRS_neuronal_DEAs.rds")[,1:3]
bulk <- readRDS("../00_stressData/CRS_bulkPvals.rds")
prop <- readRDS("../00_stressData/CRS_countsPerCluster.rds")
bulk <- bulk[intersect(names(bulk), row.names(prop))]
dea <- bbhw(dea, bulk, pb = prop)
dea <- dplyr::bind_rows(lapply(split(dea, dea$cluster_id), \(x){
  x$FDR <- p.adjust(x$p_val, method="fdr")
  x
}))
dea2 <- dea[grep("CA1|DG|Ccn2|Cntnap4", dea$cluster_id),]
dea2$cluster_id <- droplevels(dea2$cluster_id)
degs1 <- lapply(split(dea2, dea2$cluster_id), \(x) x$gene[which(x$FDR<0.05)])
degs2 <- lapply(split(dea2, dea2$cluster_id), \(x) x$gene[which(x$padj<0.05)])

m1 <- make_comb_mat(degs1,min_set_size = 3, top_n_sets = 12)
up1 <- ComplexHeatmap::UpSet(m1, column_title="Standard FDR", 
                      left_annotation = upset_left_annotation(m1, ylim=c(0,100)), right_annotation = rowAnnotation(test=anno_text(row.names(m1), just = 0.5, location=unit(0.5, 'npc'))),
                      top_annotation=HeatmapAnnotation(
              "Intersection\nsize" = anno_barplot(
                  comb_size(m1), ylim=c(0,71),
                  border = FALSE, 
                  gp = gpar(fill = "black"), 
                  height = unit(2, "cm")
              ), 
              annotation_name_side = "left", 
              annotation_name_rot = 0))

m2 <- make_comb_mat(degs2,min_set_size = 3, top_n_sets = 12)
up2 <- UpSet(m2, column_title="After bbhw", row_names_side="left", top_annotation = 
          HeatmapAnnotation(
              "Intersection\nsize" = anno_barplot(
                  comb_size(m2), ylim=c(0,71),
                  border = FALSE, 
                  gp = gpar(fill = "black"), 
                  height = unit(2, "cm"),
                  axis_param = list(side = "right")
              ), 
              annotation_name_side = "right", 
              annotation_name_rot = 0)
)

up1 + up2
```

```{r, fig.width=10, fig.height=8}
pdf("Figure5_final.pdf", width=10, height=8)
plot_grid(tpr, grid.grabExpr(draw(up1+up2), wrap.grobs=TRUE), labels=LETTERS[1:3], nrow=2, scale=c(0.95, 0.85), rel_heights = c(4,3))
dev.off()
```
