---
title: "Figure 5 "
author: "Jiayi Wang"
date: "2025-09-05"
output: html_document
---

## Dependencies
```{r}
suppressPackageStartupMessages({
    library(ggplot2)
    library(SingleCellExperiment)
    library(patchwork)
    library(ggrastr)
    library(RColorBrewer)
})
```

## UMAP of simulated dataset 2
```{r}
sce <- readRDS("../04_simulation2/data/sim/")
df <- data.frame(reducedDim(sce, "UMAP"), colData(sce))

aes <- list(
    geom_point_rast(aes(UMAP1, UMAP2), 
                    shape=16, alpha=0.1, size=0.5),
    guides(col=guide_legend(
        ncol=4, title.position="top",
        override.aes=list(alpha=1, size=2))),
    theme_minimal(6), theme(
        aspect.ratio=1,
        plot.margin=margin(),
        axis.text=element_blank(),
        panel.grid=element_blank(),
        axis.title=element_text(hjust=0),
        panel.border=element_rect(fill=NA),
        legend.key.size=unit(0.25, "lines")))


nk <- length(unique(df$cluster_id))
gg <-  ggplot(df, aes(col=group_id)) +
    scale_color_manual(values=c("royalblue", "tomato")) +
    ggplot(df, aes(col=cluster_id)) +
    scale_color_manual(values=colorRampPalette(brewer.pal(12, "Dark2"))(nk)) +
    plot_layout(nrow=1, guides="collect") & 
    aes & theme(
        plot.margin=margin(0),
        legend.justification=c(0.5, 1),
        legend.box.spacing=unit(0, "pt"),
        )
```


## Heatmap
```{r}
fs <- list.files("../04_simulation2/outs/sim/sta/", "^metrics*", full.names = TRUE)
res <- lapply(args[[1]], readRDS)
df <- do.call(rbind,res)
setDT(df)
df <- df[threshold==0.05 & size=="12_2v2",]
df <- df[!grepl("raw|^FDR$", df$method),]
.plot1 <- \(df, type = "mean") {
    d <- unique(df[,.(method, celltype, variable, value)])
    renameScores <- function(st, rmLoc=FALSE, rmRaw=TRUE, rmSig=FALSE){
        if(is.data.frame(st)){
            if(!is.null(st$score))
                st$score <- renameScores(st$score, rmLoc=rmLoc, rmRaw=rmRaw, rmSig=rmSig)
            if(!is.null(st$method))
                st$method <- renameScores(st$method, rmLoc=rmLoc, rmRaw=rmRaw, rmSig=rmSig)
            return(st)
        }
        score <- factor(st)
        levels(score) <- gsub("^padj\\.","",levels(score))
        levels(score) <- gsub("Global", "glb", levels(score), ignore.case = TRUE)
        levels(score) <- gsub("Local", "loc", levels(score), ignore.case = TRUE)
        if(rmLoc) levels(score) <- gsub("\\.loc|\\.glb","",levels(score))
        if(rmRaw) levels(score) <- gsub("\\.raw","",levels(score))
        if(rmSig) levels(score) <- gsub("sig\\.","",levels(score))
        score
    }
    d <- d[grep(type, d$variable),]
    d[,variable:= gsub(paste0(type,"."), "", variable, fixed=TRUE)]
    d[,variable := factor(variable, c("precision","recall", "F1"))]
    d$method <- renameScores(gsub("padj\\.", "", d$method))
    wPrior <- ifelse(grepl("^FDR\\.glb$|^FDR\\.loc$",d$method), "no prior", 
                     "using bulk prior")
    
    ml <- lapply(split(d, d$variable), FUN=function(x){
        m <- reshape2::dcast(x, formula = celltype~method, value.var="value")
        row.names(m) <- m[,1]
        t(m[,-1])
    })
    
    m <- do.call(cbind, lapply(ml, \(x){
        rm <- matrixStats::colMedians(x, na.rm=TRUE)
        for(i in seq_along(rm)){
            x[which(is.na(x[,i])),i] <- rm[i]
        }
        x
    }))
    
    mo <- row.names(m)[order(rowMeans(m, na.rm=TRUE) + 
                                 matrixStats::rowMedians(m, na.rm=TRUE))]
    wPrior <- ifelse(grepl("^FDR\\.glb$|^FDR\\.loc$",mo), "no prior", "using bulk prior")
    cols <- setNames(list(viridis::magma(100), viridis::inferno(100), viridis::viridis(100)),
                     names(ml))
    hl <- lapply(names(ml), FUN=function(x){
        m <- ml[[x]][mo,]
        if (min(m, na.rm=TRUE) == max(m, na.rm=TRUE)) {
            col_fun <- function(z) rep(cols[[x]][100], length(z))
        } else {
            col_fun <- circlize::colorRamp2(
                breaks = seq(min(m, na.rm=TRUE), max(m, na.rm=TRUE), length.out=100),
                colors = cols[[x]]
            )
        }
        
        Heatmap(
            m, name=x,
            cluster_columns = FALSE, cluster_rows = FALSE,
            col = col_fun,               
            column_title = x,
            column_names_gp = gpar(fontsize=9),
            row_split = wPrior,
            row_names_gp = gpar(fontsize=9)
        )
    })
    
    draw(Reduce("+", hl), merge=TRUE)
}

.plot1(df)
```


## Line plot
```{r}
res <- lapply(fs, readRDS)
df <- do.call(rbind,res)
setDT(df)
df <- df[threshold==0.05  & size != "12_2v2"]
df <- df[!grepl("raw|^FDR$", df$method),]

.plot2 <- \(df, type = "mean") {
    d <- unique(df[,.(method, celltype, variable, 
                      value, size, bin, loc, cor)])
    d <- d[grep(type, d$variable),]
    renameScores <- function(st, rmLoc=FALSE, rmRaw=TRUE, rmSig=FALSE){
        if(is.data.frame(st)){
            if(!is.null(st$score))
                st$score <- renameScores(st$score, rmLoc=rmLoc, rmRaw=rmRaw, rmSig=rmSig)
            if(!is.null(st$method))
                st$method <- renameScores(st$method, rmLoc=rmLoc, rmRaw=rmRaw, rmSig=rmSig)
            return(st)
        }
        score <- factor(st)
        levels(score) <- gsub("^padj\\.","",levels(score))
        levels(score) <- gsub("Global", "glb", levels(score), ignore.case = TRUE)
        levels(score) <- gsub("Local", "loc", levels(score), ignore.case = TRUE)
        if(rmLoc) levels(score) <- gsub("\\.loc|\\.glb","",levels(score))
        if(rmRaw) levels(score) <- gsub("\\.raw","",levels(score))
        if(rmSig) levels(score) <- gsub("sig\\.","",levels(score))
        score
    }
    
    d$method <- renameScores(gsub("padj\\.", "", d$method))
    wPrior <- ifelse(grepl("^FDR\\.glb$|^FDR\\.loc$",d$method), "no prior", 
                     "using bulk prior")
    d[,variable:= gsub(paste0(type,"."), "", variable, fixed=TRUE)]
    d[,variable := factor(variable, c("precision","recall", "F1"))]
    d <- d[variable!="precision"]
    d[,size:=factor(size)]
    
    aes <- list(
        facet_grid2(variable ~ celltype, scales = "free", independent = "y"),
        guides(col=guide_legend(
            ncol=4, title.position="top",
        )),
        theme_minimal(), theme(
            plot.margin=margin(),
            panel.grid=element_blank(),
            panel.border=element_rect(fill=NA),
            legend.key.size=unit(0.25, "lines"),
            axis.text.x = element_text(angle = 45, hjust = 1) 
        )
    )
    
    d <- d[method %in% c("FDR.loc", "PAS.LSL.loc", "sig.LSL.loc", "asNA.LSL.loc")]
    n <- length(unique(d$method))
    ggplot(d, aes(x = size, y = value, 
                  group = method, col=method)) +
        geom_line(alpha=0.8) + geom_point(size=1.5, alpha=0.8) +
        scale_color_manual(values=colorRampPalette(brewer.pal(12, "Paired"))(n)) +
        plot_layout(nrow=1, guides="collect") & 
        aes & theme(legend.position="bottom")
    
}

.plot2(df)
```

