---
title: "Figure main results"
author: "Pierre-Luc"
date: "2025-03-27"
output: html_document
---

```{r setup}
suppressPackageStartupMessages({
  library(ggplot2)
  library(patchwork)
  library(cowplot)
  library(data.table)
})
source("../functions.R")
doRelative <- FALSE
```



```{r, eval=TRUE}
load("../03_simulation1/simulated1.res.RData")
aucs1 <- aucs
simtruth <- readRDS("../03_simulation1/simulated1.truth.rds")
ssres <- lapply(ssres, \(m){
  m <- merge(m, simtruth, by=c("celltype","gene"), all.x=TRUE)
  m$isDEG <- !is.na(m$logFC.y)
  m[order(m$celltype, m$PValue),]
})
scores <- grep("^FDR|^padj\\.", colnames(ssres[[1]]), value=TRUE)
# sts2 <- dplyr::bind_rows(lapply(ssres, \(m){
#   getStats(m[,scores], m$isDEG, celltype=m$celltype, roundNd = NULL, noRankAt1=TRUE)
# }), .id="seed")
# tprPlot(sts2[which(sts2$score %in% scores),])

m <- dplyr::bind_rows(ssres, .id="seed")
sts <- getStats(m[,scores], m$isDEG, celltype=m$celltype, roundNd = NULL, noRankAt1=TRUE)
thsS <- computeMetrics(ssres, relative=doRelative)

FPsS <- dplyr::bind_rows(lapply(ssres, FUN=function(x){
  x <- x[grep("Unaffected", x$celltype),]
  for(f in scores){
    if(is.null(x[[f]])) x[[f]] <- NA_integer_
  }
  d <- dplyr::bind_rows(lapply(split(x[,scores], x$celltype), \(x){
    data.frame(method=scores, FPs=colSums(as.matrix(x)<0.05))
  }), .id="celltype")
}), .id="seed")


load("../02_MSdata/MS.res.RData")
aucs <- rbind(aucs, aucs1)
truth <- readRDS("../02_MSdata/pbfull_res.rds")
truth <- truth[!grepl("Excitatory", truth$celltype),]

m <- dplyr::bind_rows(ssres, .id="seed")
m <- merge(m, truth[,c("celltype","gene","isDEG")], by=c("celltype","gene"))
m <- m[!is.na(m$isDEG),]
scores <- grep("^FDR|^padj\\.", colnames(m), value=TRUE)
m <- m[order(m$celltype, m$PValue),]
st <- getStats(m[,scores], m$isDEG, celltype=m$celltype, roundNd = NULL, noRankAt1=TRUE)
ths <- computeMetrics(ssres, truth, relative=doRelative)

save(sts, st, ths, thsS, FPsS, aucs, file="plotDat.RData")
```


```{r, fig.width=10, fig.height=13}
load("plotDat.RData")
scores <- grep("FDR\\.local|loc\\.raw$",unique(thsS$method), value=TRUE)
st <- mergeSts(sts, st)
st <- renameScores(st[st$score %in% scores,], TRUE, TRUE, TRUE)
p1 <- tprPlot(st)

dt <- dplyr::bind_rows(list("Simulated data"=thsS, "MS data"=ths), .id="Dataset")
dt$celltype <- paste(dt$Dataset, dt$celltype, sep="\n")
dt2 <- dt[grep("FDR\\.local|loc\\.raw$",dt$method),]
dt2 <- renameScores(dt2, TRUE, TRUE, TRUE)
levels(dt2$method) <- gsub("^FDR$", "No prior", levels(dt2$method)) 
dt2$method <- relevel(dt2$method, "No prior")
pt1 <- plotThStats2(dt2)

dt <- dt[grep("FDR\\.local|LSL\\.loc",dt$method),]
dt <- renameScores(dt, TRUE, rmRaw = FALSE)
conv <- c(FDR="No prior", sig.LSL.raw="p", sig.LSL="p+sign", asNA.LSL="p+sign+asNA", combined.LSL="p+sign+combined", PAS.LSL="p+sign+PAS")
levels(dt$method) <- conv[levels(dt$method)]
dt$method <- factor(as.character(dt$method), as.character(conv))
pt2 <- plotThStats2(dt)

pdf("Figure3_main.pdf", width=10, height=13)
plot_grid( p1,
           pt1, pt2, nrow=3, rel_heights = c(4.6,3,3.5), labels=LETTERS[1:3], scale=0.95)
dev.off()
```


```{r, fig.width=10, fig.height=11}
```
