---
title: "Figure 2"
author: "Jiayi Wang"
date: "2025-10-17"
output: html_document
---

## Dependencies
```{r}
suppressPackageStartupMessages({
    library(ggplot2)
    library(SingleCellExperiment)
    library(patchwork)
    library(ggrastr)
    library(RColorBrewer)
})
```

## UMAP and proportion of simulated dataset 1 and 2
```{r}
sce <- readRDS("../04_simulation2/data/sim/00-raw/muscat_LPS.rds")
#sce <- readRDS("../04_simulation2/data/sim/00-raw/muscat_PBMC.rds") #sim2
df <- data.frame(reducedDim(sce, "UMAP"), colData(sce))

aes <- list(
    geom_point_rast(aes(UMAP1, UMAP2), 
                    shape=16, alpha=0.1, size=0.5),
    guides(col=guide_legend(
        ncol=4, title.position="top",
        override.aes=list(alpha=1, size=2))),
    theme_minimal(6), theme(
        aspect.ratio=1,
        plot.margin=margin(),
        axis.text=element_blank(),
        panel.grid=element_blank(),
        axis.title=element_text(hjust=0),
        panel.border=element_rect(fill=NA),
        legend.key.size=unit(0.25, "lines")))


nk <- length(unique(df$cluster_id))
gg <-  ggplot(df, aes(col=group_id)) +
    scale_color_manual(values=c("royalblue", "tomato")) +
    ggplot(df, aes(col=cluster_id)) +
    scale_color_manual(values=colorRampPalette(brewer.pal(12, "Dark2"))(nk)) +
    plot_layout(nrow=1, guides="collect") & 
    aes & theme(
        plot.margin=margin(0),
        legend.justification=c(0.5, 1),
        legend.box.spacing=unit(0, "pt"),
        )

cd <- as.data.table(colData(sce))
prop_dt <- cd[, .N, by = cluster_id]
prop_dt[, prop := N / sum(N)]
prop_dt[, label := sprintf("%s\n%.1f%%", cluster_id, prop * 100)]
prop_dt[, cluster_id := factor(cluster_id, levels = prop_dt[order(-prop)]$cluster_id)]

pp <- ggplot(prop_dt, aes(x = 1, y = prop, fill = cluster_id)) +
  geom_col(width = 0.1) +
  scale_fill_manual(values=colorRampPalette(brewer.pal(12, "Dark2"))(nk)) +
  geom_text(aes(label = label),
            position = position_stack(vjust = 0.5),
            size = 3, color = "black", lineheight = 0.9) +
  scale_y_continuous(limits = c(0, 1)) +
  theme_void() + 
  theme(
    legend.position = "none"
  )
```