---
title: "Figure main results"
author: "Pierre-Luc"
date: "2025-03-27"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(patchwork)
  library(cowplot)
})
source("../functions.R")
```



```{r, eval=FALSE}
load("../scRNAsimulation/simulated2.res.RData")
simtruth <- readRDS("../scRNAsimulation/simulated2.truth.rds")
m <- dplyr::bind_rows(ssres, .id="seed")
m <- merge(m, simtruth, by=c("celltype","gene"), all.x=TRUE)
m$isDEG <- !is.na(m$logFC.y)
scores <- grep("^FDR|^padj\\.", colnames(m), value=TRUE)
m <- m[order(m$celltype, m$PValue),]
sts <- getStats(m[,intersect(scores,colnames(m))], m$isDEG, celltype=m$celltype, roundNd = NULL, noRankAt1=TRUE)
thsS <- getThStats(ssres, simtruth)

FPsS <- dplyr::bind_rows(lapply(ssres, FUN=function(x){
  x <- x[grep("Unaffected", x$celltype),]
  for(f in scores){
    if(is.null(x[[f]])) x[[f]] <- NA_integer_
  }
  d <- dplyr::bind_rows(lapply(split(x[,scores], x$celltype), \(x){
    data.frame(method=scores, FPs=colSums(as.matrix(x)<0.05))
  }), .id="celltype")
}), .id="seed")


load("../MSdata/MS.res.RData")
truth <- readRDS("../MSdata/pbfull_res.rds")
truth <- truth[!grepl("Excitatory", truth$celltype),]
m <- dplyr::bind_rows(ssres, .id="seed")
m <- merge(m, truth[,c("celltype","gene","isDEG")], by=c("celltype","gene"))
m <- m[!is.na(m$isDEG),]
scores <- grep("^FDR|^padj\\.", colnames(m), value=TRUE)
m <- m[order(m$celltype, m$PValue),]
st <- getStats(m[,intersect(scores,colnames(m))], m$isDEG, celltype=m$celltype, roundNd = NULL, noRankAt1=TRUE)
ths <- getThStats(ssres, truth)

save(sts, st, ths, thsS, FPsS, file="plotDat.RData")
```


```{r, fig.width=10, fig.height=11}
load("plotDat.RData")
scores <- grep("FDR\\.local|loc\\.raw$",unique(thsS$method), value=TRUE)
sts2 <- renameScores(sts[sts$score %in% scores,], TRUE, TRUE, TRUE)
p1 <- plotPR(sts2, facet_scores = FALSE, noLine = TRUE, nrow=1) + 
  labs(title="Simulated data", x="Recall (i.e. sensitivity)", y="Precision (1-FDR)")
st2 <- renameScores(st[st$score %in% scores,], TRUE, TRUE, TRUE)
p2 <- plotPR(st2, facet_scores = FALSE, noLine = TRUE, nrow=1) +
  labs(title="Subsampled MS data", x="Recall (i.e. sensitivity)", y="Precision (1-FDR)")

dt <- dplyr::bind_rows(list("Simulated data"=thsS, "MS data"=ths), .id="Dataset")
dt$celltype <- paste(dt$Dataset, dt$celltype, sep="\n")
dt2 <- dt[grep("FDR\\.local|loc\\.raw$",dt$method),]
dt2 <- renameScores(dt2, TRUE, TRUE, TRUE)
levels(dt2$method) <- gsub("^FDR$", "No prior", levels(dt2$method)) 
dt2$method <- relevel(dt2$method, "No prior")
pt1 <- plotThStats(dt2)

dt <- dt[grep("FDR\\.local|LSL\\.loc",dt$method),]
dt <- renameScores(dt, TRUE, rmRaw = FALSE)
conv <- c(FDR="No prior", sig.LSL.raw="p", sig.LSL="p+sign", asNA.LSL="p+sign+asNA", combined.LSL="p+sign+combined", PAS.LSL="p+sign+PAS")
levels(dt$method) <- conv[levels(dt$method)]
dt$method <- factor(as.character(dt$method), as.character(conv))
pt2 <- plotThStats(dt)

pdf("Figure3_main.pdf", width=10, height=11)
plot_grid( (p1/ p2) + plot_layout(guides="collect"),
           pt1, pt2, nrow=3, rel_heights = c(5,2.7,3), labels=LETTERS[1:3], scale=0.95)
dev.off()
```
